baseURL = "/"
languageCode = "en-us"
title = "Hi, I'm Princiya"
theme = "kube"
description = "I <3 Food & JavaScript!"
Paginate = 5
[Params]
  RSSLink = "/index.xml"
  author = "Princiya" # add your company name
  github = "princiya" # add your github profile name
  twitter = "princi_ya" # add your twitter profile
  email = "hello@princiya.com"

[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
